### PR TITLE
Add redirects: Scribe ==> VolSync

### PR DESCRIPTION
**Pull request by JohnStrunk**
**Describe what this PR does**
The Scribe project is being renamed to VolSync. With that rename, the repo and docs are moving. This PR adds notices and points people to the new location.

- [x] Main README
- [x] scribe-replication.readthedocs.io
- [x] Helm chart description

**Is there anything that requires special attention?**

**Related issues:**

Related to #217

### CODE REVIEW

**Comment by screeley44** [comment]
@JohnStrunk - I threw#219 up there as an example which is based on what they did with `community operators` - so I like the big warning image - so it's obvious to users, maybe add that in?

and I think it would be beneficial to remove the rest of the readme...don't even give them a chance to read anything about the project until they click to the new link

And then after the final switch we can just archive as read-only

**Comment by screeley44** [comment]
I'd do the same with helm readme and the index.rst - IMHO

**Comment by JohnStrunk** [comment]
I adjusted the main + helm readme, and I also added a banner to all the docs pages.

**Comment by JohnStrunk** [comment]
@screeley44 I think this is ready for another look

**Review by screeley44 — APPROVED** [review]
LGTM

**Pull request merged**
