### PR TITLE
Get the operator working on OpenShift

### LINKED ISSUE #16: Support for OpenShift
**Describe the feature you'd like to have.**
Scribe should support OpenShift.

**What is the value to the end user? (why is it a priority?)**

**How will we know we have a good solution? (acceptance criteria)**

**Additional context**

Known items:
* There will need to be work on SCCs to ensure the mover pods can run with sufficient privileges.

### PR DESCRIPTION
**Pull request by JohnStrunk**
**Describe what this PR does**
Attempts to get the operator functioning in-cluster on OpenShift

**Is there anything that requires special attention?**

**Related issues:**
Fixes #16

### CODE REVIEW

**Comment by JohnStrunk** [comment]
The operator is running, but jobs don't start due to a lack of SCC.
Time to figure out how to incorporate #24 into the deployment.

**Comment by JohnStrunk** [comment]
This seems to work at this point... I've seen some anomalies in the reconcile sequence (src job gets restarted prior to next interval),  but the operator seems to fix it when the interval happens. I suspect object caching is causing the problem, but :man_shrugging: .

Still to do: move the rbac to a separate file.

**Comment by JohnStrunk** [comment]
@backube/scribemaintainers - I think this is ready

**Comment by cooktheryan** [comment]
@JohnStrunk going to review now

**Review by cooktheryan — APPROVED** [review]
Code works on OCP!!!

**Pull request merged**
