### PR TITLE
Upgrade to operator-sdk 1.7.2

### LINKED ISSUE #175: Upgrade operator-sdk to v1.7
**Describe the feature you'd like to have.**
Upgrade the version of operator-sdk we're using to v1.7

**What is the value to the end user? (why is it a priority?)**

**How will we know we have a good solution? (acceptance criteria)**

**Additional context**
This is related to #12 as it will also include upgrading the project scaffolding and controller-runtime versions as well.

### PR DESCRIPTION
**Pull request by JohnStrunk**
**Describe what this PR does**
This upgrades Scribe to be based on operator-sdk 1.7.1

**Is there anything that requires special attention?**
Upgrade was performed by re-scaffolding the project and copying items over.

**Related issues:**
Fixes #175

### CODE REVIEW

**Comment by JohnStrunk** [comment]
@backube/scribemaintainers There are 3 commits here...
* The 1st is the actual upgrade to 1.7.2. There's not much code change, but lots of yaml/kustomize changes. I tried to get everything copied over & updated, but I may have missed something.
* The last 2 are related to the cli (@sallyom). This builds the cli in the CI environment then does a simple migration test using it in the e2e.

**Comment by JohnStrunk** [comment]
I'm putting this back up for review after pulling out the cli e2e and opening #180 and #181.

**Review by sallyom — APPROVED** [review]

**Pull request merged**
