### PR TITLE
needing to specify the ability to run as any user and a user

### LINKED ISSUE #183: Cannot run on OpenShift
**Describe the bug**
Manager pod won't start

**Steps to reproduce**
1) Pull down master branch
2) make deploy-openshift
3) err
```
48m         Warning   Failed              pod/scribe-controller-manager-795bf4bbc5-5fqp7    Error: container create failed: time="2021-05-14T16:49:55Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied"
```
**Expected behavior**
Container runs

**Actual results**
Manager container cant start

**Additional context**
Reference https://bugzilla.redhat.com/show_bug.cgi?id=1934177

I dont know if we will just need to keep this as a work around or if this may have to be in longer term.

### PR DESCRIPTION
**Pull request by cooktheryan**
Signed-off-by: Ryan Cook <rcook@redhat.com>

**Describe what this PR does**
Resolves #183 

**Is there anything that requires special attention?**
Is this the best route to resolve the issue?

**Related issues:**
#183

### CODE REVIEW

**Comment by cooktheryan** [comment]
@JohnStrunk I have a new OCP cluster if you want to try this or test other variations

**Comment by JohnStrunk** [comment]
From the BZ, this looks like it was caused by a regression in OCP, and is now fixed in all supported versions. I'm not sure we should integrate this hack that will leave us running w/ `anyuid` SCC instead of `restricted`.

If we do go forward with this:
From a review standpoint, changes to the `config/` manifests also need to be reflected in the helm chart. The runAsUser can be put into the values.yaml, and I'm not sure if the Role needs to be updated. We already have access to the mover SCC (since we have to enable it for the mover pods), so we're probably not restricted.

**Comment by cooktheryan** [comment]
Ok I ran this against 4.7.4 and am patching to 4.7.9 let me see if there is
a resolution there.


Ryan

**Comment by cooktheryan** [comment]
```
master└─ $ make deploy-openshift
/tmp/scribe/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
cp config/crd/bases/* helm/scribe/crds
cd config/manager && /tmp/scribe/bin/kustomize edit set image controller=quay.io/backube/scribe:latest
/tmp/scribe/bin/kustomize build config/openshift | kubectl apply -f -
namespace/scribe-system created
customresourcedefinition.apiextensions.k8s.io/replicationdestinations.scribe.backube created
customresourcedefinition.apiextensions.k8s.io/replicationsources.scribe.backube created
serviceaccount/scribe-controller-manager created
role.rbac.authorization.k8s.io/scribe-leader-election-role created
clusterrole.rbac.authorization.k8s.io/scribe-manager-role created
clusterrole.rbac.authorization.k8s.io/scribe-metrics-reader created
clusterrole.rbac.authorization.k8s.io/scribe-proxy-role created
rolebinding.rbac.authorization.k8s.io/scribe-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/scribe-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/scribe-proxy-rolebinding created
configmap/scribe-manager-config created
service/scribe-controller-manager-metrics-service created
deployment.apps/scribe-controller-manager created
securitycontextconstraints.security.openshift.io/scribe-mover unchanged
rcook (scribe-system/api-failover-octo-emerging-redhataicoe-com:6443/system:admin)  @ /tmp/scribe
master└─ $ oc get po
oNAME                                         READY   STATUS                 RESTARTS   AGE
scribe-controller-manager-795bf4bbc5-qrwj7   1/2     CreateContainerError   0          23s
crcook (scribe-system/api-failover-octo-emerging-redhataicoe-com:6443/system:admin)  @ /tmp/scribe
master└─ $ oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.7.9     True        False         29m     Cluster version is 4.7.9
rcook (scribe-system/api-failover-octo-emerging-redhataicoe-com:6443/system:admin)  @ /tmp/scribe
master└─ $ oc get events
LAST SEEN   TYPE      REASON              OBJECT                                            MESSAGE
41s         Normal    LeaderElection      configmap/b95b3104.backube                        scribe-controller-manager-795bf4bbc5-qrwj7_ad4c2323-baf0-41c4-b012-1e0bfa2d220c became leader
41s         Normal    LeaderElection      lease/b95b3104.backube                            scribe-controller-manager-795bf4bbc5-qrwj7_ad4c2323-baf0-41c4-b012-1e0bfa2d220c became leader
47s         Normal    Scheduled           pod/scribe-controller-manager-795bf4bbc5-qrwj7    Successfully assigned scribe-system/scribe-controller-manager-795bf4bbc5-qrwj7 to ip-10-0-197-225.us-west-2.compute.internal
46s         Normal    AddedInterface      pod/scribe-controller-manager-795bf4bbc5-qrwj7    Add eth0 [10.131.0.17/23]
3s          Normal    Pulled              pod/scribe-controller-manager-795bf4bbc5-qrwj7    Container image "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0" already present on machine
45s         Warning   Failed              pod/scribe-controller-manager-795bf4bbc5-qrwj7    Error: container create failed: time="2021-05-14T18:37:56Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied"
45s         Normal    Pulling             pod/scribe-controller-manager-795bf4bbc5-qrwj7    Pulling image "quay.io/backube/scribe:latest"
44s         Normal    Pulled              pod/scribe-controller-manager-795bf4bbc5-qrwj7    Successfully pulled image "quay.io/backube/scribe:latest" in 1.013145749s
44s         Normal    Created             pod/scribe-controller-manager-795bf4bbc5-qrwj7    Created container manager
44s         Normal    Started             pod/scribe-controller-manager-795bf4bbc5-qrwj7    Started container manager
43s         Warning   Failed              pod/scribe-controller-manager-795bf4bbc5-qrwj7    Error: container create failed: time="2021-05-14T18:37:57Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied"
42s         Warning   Failed              pod/scribe-controller-manager-795bf4bbc5-qrwj7    Error: container create failed: time="2021-05-14T18:37:58Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied"
30s         Warning   Failed              pod/scribe-controller-manager-795bf4bbc5-qrwj7    Error: container create failed: time="2021-05-14T18:38:11Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied"
18s         Warning   Failed              pod/scribe-controller-manager-795bf4bbc5-qrwj7    Error: container create failed: time="2021-05-14T18:38:23Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied"
3s          Warning   Failed              pod/scribe-controller-manager-795bf4bbc5-qrwj7    Error: container create failed: time="2021-05-14T18:38:38Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied"
48s         Normal    SuccessfulCreate    replicaset/scribe-controller-manager-795bf4bbc5   Created pod: scribe-controller-manager-795bf4bbc5-qrwj7
48s         Normal    ScalingReplicaSet   deployment/scribe-controller-manager              Scaled up replica set scribe-controller-manager-795bf4bbc5 to 1
51s         Normal    CreatedSCCRanges    namespace/scribe-system                           created SCC ranges```

**Comment by cooktheryan** [comment]
Looks like fixed in 4.6 nightly. Checking 4.7 now
```
master└─ $ oc get clusterversion
NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.6.0-0.nightly-2021-05-14-012001   True        False         51m     Cluster version is 4.6.0-0.nightly-2021-05-14-012001
rcook (admin)  @ /tmp/scribe
master└─ $ make deploy-openshift
/tmp/scribe/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
cp config/crd/bases/* helm/scribe/crds
cd config/manager && /tmp/scribe/bin/kustomize edit set image controller=quay.io/backube/scribe:latest
/tmp/scribe/bin/kustomize build config/openshift | kubectl apply -f -
namespace/scribe-system created
customresourcedefinition.apiextensions.k8s.io/replicationdestinations.scribe.backube created
customresourcedefinition.apiextensions.k8s.io/replicationsources.scribe.backube created
serviceaccount/scribe-controller-manager created
role.rbac.authorization.k8s.io/scribe-leader-election-role created
clusterrole.rbac.authorization.k8s.io/scribe-manager-role created
clusterrole.rbac.authorization.k8s.io/scribe-metrics-reader created
clusterrole.rbac.authorization.k8s.io/scribe-proxy-role created
rolebinding.rbac.authorization.k8s.io/scribe-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/scribe-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/scribe-proxy-rolebinding created
configmap/scribe-manager-config created
service/scribe-controller-manager-metrics-service created
deployment.apps/scribe-controller-manager created
securitycontextconstraints.security.openshift.io/scribe-mover created
rcook (admin)  @ /tmp/scribe
master└─ $ oc get po -w -n scribe-system
NAME                                         READY   STATUS              RESTARTS   AGE
scribe-controller-manager-795bf4bbc5-nq799   0/2     ContainerCreating   0          11s
scribe-controller-manager-795bf4bbc5-nq799   1/2     Running             0          15s
scribe-controller-manager-795bf4bbc5-nq799   2/2     Running             0          21s
```

**Comment by JohnStrunk** [comment]
Should be 4.7.11 that got the fix.

**Comment by cooktheryan** [comment]
@JohnStrunk going to just close the issue and PR

**Comment by cooktheryan** [comment]
same for 4.7 nightly. We just will wait before cutting the 0.2.0 release

**Pull request closed without merging**
