### PR TITLE
Create mover Interface to start isolating mover code

### PR DESCRIPTION
**Pull request by JohnStrunk**
**Describe what this PR does**
This is another attempt at refactoring the controller code to reduce duplication. The experience of continuing to work on #171 has led be to the conclusion that what I was trying to do, while decreasing the line count and duplication, was just making the code more complicated.

This is a different approach where I'm going to try to reduce the duplication between source & destination, but not between movers. The general approach will be to take the API types and use them to initialize state for a common FooReconciler object that can reconcile both source and destination. As a part of this, I'm also splitting out each mover into its own file so that the `*_controller.go` files are so hard to navigate.

List of high-level changes:
- [x] Move VolumeHandler code to a new package and unify source/dest code
- [x] Create a Mover Interface (thanks for the suggestion @guymguym)
- [x] Switch to 2-phase reconcile (sync and cleanup) based on schedule
  - [x] Properly handle empty schedule by adding reconcile "Condition"
- [x] Re-write Restic using new Mover Interface
- [x] Make SAHandler more generic and move to its own package
- [x] Move Restic to its own Mover package
- [x] Add tests for Restic

**Is there anything that requires special attention?**

Moving Rsync & Rclone to use the Mover/Builder interfaces will be done in separate PRs. This will also permit cleaning up the main controller reconcile loops by only reconciling based on movers that are present in the (new) Catalog.

**Related issues:**
Related to #160, #171

### CODE REVIEW

**Comment by JohnStrunk** [comment]
@backube/scribemaintainers I'm marking this ready. Hopefully the walkthrough in our last meeting made this a bit easier to look at. :scream:

**Review by sallyom — APPROVED** [review]
This PR/refactor was discussed & reviewed as a team, I've gone through it here as well. If we're all good with this, let's merge it!

**Pull request merged**
