### PR TITLE
Add link to rclone website in README file

### PR DESCRIPTION
**Pull request by mykaul**
**Describe what this PR does**
add a hyperlink to rclone website in the readme file.

### CODE REVIEW

**Comment by JohnStrunk** [comment]
Yaniv, could you please add a signoff to your commit indicating compliance w/ [DCO](https://developercertificate.org/).

```
git commit -s --amend
git push --force
```

**Comment by mykaul** [comment]
> Yaniv, could you please add a signoff to your commit indicating compliance w/ [DCO](https://developercertificate.org/).
> 
> ```
> git commit -s --amend
> git push --force
> ```

I've used the Github UI to create this patch. Could not figure out how to edit that commit. I'll just redo it properly.

**Review by husky-parul — DISMISSED** [review]
LGTM

**Comment by JohnStrunk** [comment]
Closing since we have renamed and moved to the [VolSync repo](https://github.com/backube/volsync).

**Pull request closed without merging**
